### ISSUE TITLE
this mod can't work on fabric 0.14.21 minecraft version 1.19.4

### ISSUE THREAD

**Issue by minecraft-99999** [FabricMC/fabric-language-kotlin#110]

**Comment by minecraft-99999** [comment]
the error code is 1

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
