### ISSUE TITLE
installed most updated version of kotlin, but keep getting error ending in: only the wrong version is present: 0.14.19

### ISSUE THREAD

**Issue by tugggert** [FabricMC/fabric-language-kotlin#113]
Prism Launcher version: 7.1

Launched instance in online mode

authserver.mojang.com resolves to:
    [18.239.199.110, 18.239.199.52, 18.239.199.10, 18.239.199.19]

session.minecraft.net resolves to:
    [2620:1ec:46::69, 2620:1ec:bdf::69, 13.107.213.69, 13.107.246.69]

textures.minecraft.net resolves to:
    [2620:1ec:bdf::69, 2620:1ec:46::69, 13.107.246.69, 13.107.213.69]

api.mojang.com resolves to:
    [2620:1ec:46::69, 2620:1ec:bdf::69, 13.107.246.69, 13.107.213.69]

Minecraft folder is:
/home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/Fabulously Optimized(2)/minecraft

Java path is:
/app/jdk/17/bin/java

Java is version 17.0.7, using 64 (amd64) architecture, from Flathub.

AMD Custom APU 0405
Advanced Micro Devices, Inc. [AMD/ATI] VanGogh [AMD Custom GPU 0405] (rev ae)

Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] Device 0123

Kernel driver in use: amdgpu

OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.1.1 (git-fa55e3c026)

Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/Fabulously Optimized(2)/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw-natives-linux/3.3.2-lwjgl.1/lwjgl-glfw-natives-linux-3.3.2-lwjgl.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc-natives-linux/3.3.1/lwjgl-jemalloc-natives-linux-3.3.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-natives-linux/3.3.1/lwjgl-natives-linux-3.3.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-openal-natives-linux/3.3.1/lwjgl-openal-natives-linux-3.3.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl-natives-linux/3.3.1/lwjgl-opengl-natives-linux-3.3.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-stb-natives-linux/3.3.1/lwjgl-stb-natives-linux-3.3.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd-natives-linux/3.3.1/lwjgl-tinyfd-natives-linux-3.3.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/mojang/logging/1.0.0/logging-1.0.0.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/github/oshi/oshi-core/5.8.5/oshi-core-5.8.5.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/java/dev/jna/jna/5.10.0/jna-5.10.0.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/java/dev/jna/jna-platform/5.10.0/jna-platform-5.10.0.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.17.1/log4j-slf4j18-impl-2.17.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/ibm/icu/icu4j/70.1/icu4j-70.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/io/netty/netty-common/4.1.77.Final/netty-common-4.1.77.Final.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/io/netty/netty-buffer/4.1.77.Final/netty-buffer-4.1.77.Final.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/io/netty/netty-codec/4.1.77.Final/netty-codec-4.1.77.Final.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/io/netty/netty-handler/4.1.77.Final/netty-handler-4.1.77.Final.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/io/netty/netty-resolver/4.1.77.Final/netty-resolver-4.1.77.Final.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/io/netty/netty-transport/4.1.77.Final/netty-transport-4.1.77.Final.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/io/netty/netty-transport-native-unix-common/4.1.77.Final/netty-transport-native-unix-common-4.1.77.Final.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/io/netty/netty-transport-classes-epoll/4.1.77.Final/netty-transport-classes-epoll-4.1.77.Final.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/io/netty/netty-transport-native-epoll/4.1.77.Final/netty-transport-native-epoll-4.1.77.Final-linux-x86_64.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/io/netty/netty-transport-native-epoll/4.1.77.Final/netty-transport-native-epoll-4.1.77.Final-linux-aarch_64.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/mojang/datafixerupper/5.0.28/datafixerupper-5.0.28.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/mojang/authlib/3.11.49/authlib-3.11.49.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/httpcomponents/httpcore/4.4.14/httpcore-4.4.14.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/logging/log4j/log4j-api/2.17.1/log4j-api-2.17.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/apache/logging/log4j/log4j-core/2.17.1/log4j-core-2.17.1.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/mojang/text2speech/1.16.7/text2speech-1.16.7.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/fabricmc/intermediary/1.19.2/intermediary-1.19.2.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.12.4+mixin.0.8.5/sponge-mixin-0.12.4+mixin.0.8.5.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/fabricmc/tiny-remapper/0.8.2/tiny-remapper-0.8.2.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/ow2/asm/asm/9.4/asm-9.4.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/ow2/asm/asm-analysis/9.4/asm-analysis-9.4.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/ow2/asm/asm-commons/9.4/asm-commons-9.4.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/ow2/asm/asm-tree/9.4/asm-tree-9.4.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/org/ow2/asm/asm-util/9.4/asm-util-9.4.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/net/fabricmc/fabric-loader/0.14.19/fabric-loader-0.14.19.jar
  /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/libraries/com/mojang/minecraft/1.19.2/minecraft-1.19.2-client.jar

Native libraries:

Mods:
  [✔] [FABRIC]oresdropmores3-1.3.0-1.19.2
  [✔] [Universal]Immersive Structures-2.0.7a
  [✔] [Universal]Immersive_Structure_Nether_v1.0.0b
  [✔] AdditionalStructures-1.19.x-(v.4.1.1)
  [✔] advancementinfo-1.19.1-fabric0.58.5-1.3.1
  [✔] AmbientEnvironment-fabric-1.19.2-8.0+3
  [✔] AmbientSounds_FABRIC_v5.2.13_mc1.19.2
  [✔] animal_feeding_trough-1.0.3+1.19.2
  [✔] animatica-0.5+1.19
  [✔] antighost-1.19.1-fabric0.58.5-1.1.5
  [✘] appleskin-fabric-mc1.19-2.4.1.jar (disabled)
  [✔] architectury-6.5.85-fabric
  [✘] areas-1.19.2-5.0.jar (disabled)
  [✔] auditory-0.0.4-1.19.x
  [✔] autohud-3.2.1+1.19.1
  [✔] BambooEverything-fabric-2.2.4-build.33+mc1.19.2
  [✔] bclib-2.1.7
  [✔] bclib-jsonifier-1.0+1.19.2
  [✔] better-end-2.1.6
  [✔] better-nether-7.1.4
  [✔] bettermounthud-1.2.0
  [✘] betterstats-2.9.3+1.19.2.jar (disabled)
  [✔] BetterThirdPerson-Fabric-1.19-1.9.0
  [✔] blur-2.6.0
  [✔] borderless-mining-1.1.5+1.19
  [✔] camerautils-1.19.2-1.0.3
  [✔] Campanion-fabric-1.19.2-4.1.2+fabric
  [✔] campchair-fabric.1.19-1.0.2
  [✔] campsite_structures-1.19.2-FABRIC-1.0.3
  [✔] capes-1.5.2+1.19.2-fabric
  [✔] cardinal-components-api-5.0.2
  [✔] cem-0.7.3-1.19
  [✔] Chunky-1.3.38
  [✔] cinderscapes-3.0.6
  [✔] CITResewn-1.1.2+1.19.2
  [✔] cloth-config-8.2.88-fabric
  [✔] clutter-1.19.2-0.2.1
  [✔] collective-1.19.2-6.62
  [✔] colormatic-3.1.2+mc.1.19
  [✔] Continents_1.19_v1.1.2
  [✔] continuity-2.0.2+1.19
  [✘] Controller Support-1.19.2-8.0.4.1-Fabric.jar (disabled)
  [✔] CorgiLib-fabric-1.19.2-1.0.0.34
  [✔] cozy-1.1.0-fabric
  [✔] CreativeCore_FABRIC_v2.9.4_mc1.19.2
  [✔] crittersandcompanions-fabric-1.19.2-2.0.1
  [✔] Croptopia-1.19.2-FABRIC-2.2.2
  [✔] ctov-3.2.5
  [✔] CullLessLeaves-1.0.6
  [✔] dawn-3.5.0
  [✔] Debugify-2.8.0
  [✔] DiagonalFences-v4.2.5-1.19.2-Fabric
  [✔] dynamic-fps-2.2.0
  [✔] dynamiccrosshair-5.6.2+1.19.2-fabric
  [✔] dynamiccrosshair-compat-3.3.3+1.19.2
  [✔] EasyAnvils-v4.0.11-1.19.2-Fabric
  [✔] EasyMagic-v4.3.3-1.19.2-Fabric
  [✔] ecologics-fabric-1.19.2-2.1.11
  [✔] ecotones-0.9.1
  [✔] effective-1.4
  [✔] emi_farmersdelight-1.0.1
  [✔] emi-1.0.6+1.19.2+fabric
  [✔] emicompat-2.0.3
  [✔] emiffect-0.1.5+mc1.19.2
  [✔] EnchantingInfuser-v4.2.2-1.19.2-Fabric
  [✔] enhancedblockentities-0.7.2+1.19.2
  [✔] entity_texture_features_fabric_1.19.2-4.4.4
  [✔] entityculling-fabric-1.6.1-mc1.19.2
  [✔] ExplorersCompass-1.19.2-2.2.0-fabric
  [✔] explorify-fabric-1.19-1.3.0
  [✔] extra-mod-integrations-0.1.2+1.19.2
  [✔] extrasounds-2.3.1+1.19.2-1.19.1
  [✔] fabric-api-0.76.0+1.19.2
  [✔] fabric-language-kotlin-1.10.0+kotlin.1.9.0
  [✔] fabric-seasons-2.2.1+1.19
  [✔] fabric-seasons-croptopia-2.2.2-compat-1.0
  [✔] fabricskyboxes-0.6.2+mc1.19.2
  [✔] fabrishot-1.9.2
  [✔] FallingTree-1.19.2-3.10.0
  [✔] farmers-delight-fabric-1.19.X-1.3.9
  [✔] farsight-fabric-1.19.2-3.5
  [✘] Fastload+1.18.2-1.20-3.4.0.jar (disabled)
  [✔] ferritecore-5.0.3-fabric
  [✘] FishAreCool-0.1-1.19.2.jar (disabled)
  [✔] Fishingreal-1.19.2-1.5
  [✔] fishontheline-1.19.2-3.0
  [✔] ForgeConfigAPIPort-v4.2.11-1.19.2-Fabric
  [✔] framework-fabric-1.19.2-0.6.7
  [✔] fsb-interop-1.1.3+mc1.19.2-build.25
  [✔] geckolib-fabric-1.19-3.1.40
  [✔] geophilic-1.19-2.0.0c
  [✔] go-fish-1.6.0-1.19.1
  [✔] Good Ending-1.19.2-1.0.2-fabric
  [✔] Incendium_1.19.3_v5.1.6
  [✔] indium-1.0.9+mc1.19.2
  [✔] iris-mc1.19.2-1.6.4
  [✔] item-model-fix-1.0.3+1.19
  [✔] Jade-1.19.1-fabric-8.7.3
  [✔] jamd-fabric-2.0.5-build.12+mc1.19.2
  [✘] jeed-1.19.2-2.1.4-fabric.jar (disabled)
  [✔] jei-1.19.2-fabric-11.6.0.1016
  [✔] journeymap-1.19.2-5.9.7-fabric
  [✘] JustEnoughFarmersRecipes-1.19-1.0.1.jar (disabled)
  [✔] JustEnoughResources-Fabric-1.19.2-1.2.2.200
  [✔] kubejs-fabric-1902.6.0-build.142
  [✔] lambdabettergrass-1.3.0+1.19
  [✔] lambdynamiclights-2.2.0+1.19.2
  [✔] language-reload-1.5.8+1.19.2
  [✔] lazydfu-0.1.3
  [✔] lithium-fabric-mc1.19.2-0.11.1
  [✔] main-menu-credits-1.1.2
  [✔] memoryleakfix-fabric-1.17+-1.0.0
  [✔] midnightcontrols-1.7.4+1.19
  [✔] midnightlib-fabric-1.0.0
  [✔] MixinConflictHelper-1.2.0
  [✔] mixintrace-1.1.1+1.17
  [✔] modmenu-4.1.2
  [✔] moonlight-1.19.2-2.2.43-fabric
  [✔] morechathistory-1.19.1-1.1.1
  [✔] naturalist-fabric-3.0.3a-1.19.2
  [✔] NaturesCompass-1.19.2-2.1.0-fabric
  [✔] NoChatReports-FABRIC-1.19.2-v1.13.12
  [✘] nofade-1.18-2.0.1.jar (disabled)
  [✔] not-just-biomes-mc1.19.2-1.0.1
  [✔] Nullscape_1.19.3_v1.2.1a
  [✔] Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.1.4
  [✔] Philips-Ruins1.19.2-6.7[Fabric]
  [✔] phosphor-fabric-mc1.19.x-0.8.1
  [✔] PickUpNotifier-v4.2.4-1.19.2-Fabric
  [✔] portablemobs-1.1.2-fabric-mc1.19.2
  [✔] PresenceFootsteps-1.6.4
  [✔] promenade-2.7.1
  [✔] puzzle-1.4.2-1.19
  [✔] PuzzlesLib-v4.4.3-1.19.2-Fabric
  [✘] randomvillagenames-1.19.2-3.2.jar (disabled)
  [✔] recast-1.19.2-3.0
  [✔] reeses_sodium_options-1.4.9+mc1.19.2-build.67
  [✔] rhino-fabric-1902.2.2-build.268
  [✔] Rrls-1.19.2-3.1.1-fabric
  [✔] satin-1.9.0
  [✘] ShoulderSurfing-Fabric-1.19.2-2.4.jar (disabled)
  [✘] showdurability-1.1.0+1.19.jar (disabled)
  [✔] SimpleCopperPipes-1.13.3-1.19
  [✔] SkyVillages-1.0.2.1-1.19.x-fabric
  [✔] smarterfarmers-1.19.2-1.7.2-fabric
  [✔] smoothboot-fabric-1.19-1.7.1
  [✔] snow-under-trees-fabric-1.0.0+1.19.2
  [✔] sodium-extra-0.4.16+mc1.19.2-build.90
  [✔] sodium-fabric-mc1.19.2-0.4.4+build.18
  [✔] soundphysics-fabric-1.19.2-1.0.18
  [✔] sprout-1.4.4-fabric
  [✔] supermartijn642configlib-1.1.7-fabric-mc1.19
  [✔] supermartijn642corelib-1.1.10b-fabric-mc1.19.2
  [✔] tectonic-mod-mc1.19.2-v1.1.10
  [✔] TerraBlender-fabric-1.19.2-2.0.1.166
  [✔] Terralith_1.19.3_v2.3.8
  [✔] terrestria-5.0.11
  [✔] Towns-and-Towers-v.1.10.1-FABRIC-1.19.2
  [✔] TradingPost-v4.2.0-1.19.2-Fabric
  [✔] travelers-backpack-1.19.2-8.2.25
  [✔] TravelersTitles-1.19.2-Fabric-3.1.0
  [✔] traverse-6.0.8
  [✔] UnionLib-1.19.2-8.0.1.1-Fabric
  [✔] UniversalBoneMeal-v4.2.0-1.19.2-Fabric
  [✔] Variety_Aquatic-fabric-1.19.2-1.0.4.8
  [✔] VarietyAPI-1.0
  [✔] varietybirds-1.0-SNAPSHOT
  [✔] villagebellrecipe-1.19.2-3.0
  [✔] VisualWorkbench-v4.2.4-1.19.2-Fabric
  [✔] WWOO-FABRIC-3.1.9.1
  [✔] YetAnotherConfigLib-2.2.0-for-1.19.2
  [✔] yosbr-0.1.2
  [✔] YungsApi-1.19.2-Fabric-3.8.9
  [✔] YungsBetterDesertTemples-1.19.2-Fabric-2.2.2
  [✔] YungsBetterDungeons-1.19.2-Fabric-3.2.1
  [✔] YungsBetterMineshafts-1.19.2-Fabric-3.2.0
  [✔] YungsBetterNetherFortresses-1.19.2-Fabric-1.0.5
  [✔] YungsBetterOceanMonuments-1.19.2-Fabric-2.1.0
  [✔] YungsBetterStrongholds-1.19.2-Fabric-3.2.0
  [✔] YungsBetterWitchHuts-1.19.2-Fabric-2.1.0
  [✔] YungsBridges-1.19.2-Fabric-3.1.0
  [✔] YungsExtras-1.19.2-Fabric-3.1.0
  [✔] Zoomify-2.9.0

Params:
  --username  --version 1.19.2 --gameDir /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/Fabulously Optimized(2)/minecraft --assetsDir /home/deck/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/assets --assetIndex 1.19 --uuid  --accessToken  --userType  --versionType release

Window size: max (if available)

Launcher: standard

Java Arguments:
[-Xms512m, -Xmx4096m, -Duser.language=en]

Minecraft process ID: 440

[02:23:30] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.19
[02:23:30] [ForkJoinPool-1-worker-1/WARN]: Mod naturalist uses the version 3.0.3a which isn't compatible with Loader's extended semantic version format (Could not parse version number component '3a'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[02:23:30] [ForkJoinPool-1-worker-5/WARN]: Mod imst uses the version 2.0.7a which isn't compatible with Loader's extended semantic version format (Could not parse version number component '7a'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[02:23:31] [main/INFO]: Dependencies overridden for minecraft, fabricloader, cem, colormatic, debugify
[02:23:31] [main/WARN]: Mod resolution failed
[02:23:31] [main/INFO]: Immediate reason: [HARD_DEP capes 1.5.2+1.19.2 {depends fabric-language-kotlin @ [*]}, HARD_DEP_NO_CANDIDATE fabric-language-kotlin 1.10.0+kotlin.1.9.0 {depends fabricloader @ [>=0.14.21]}, ROOT_FORCELOAD_SINGLE capes 1.5.2+1.19.2]
[02:23:31] [main/INFO]: Reason: [HARD_DEP fabric-language-kotlin 1.10.0+kotlin.1.9.0 {depends fabricloader @ [>=0.14.21]}]
[02:23:31] [main/INFO]: Fix: add [], remove [], replace [[fabricloader 0.14.19] -> add:fabricloader 0.14.21 ([[0.14.21,∞)])]
[02:23:31] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Fabric Loader' (fabricloader) 0.14.19 with version 0.14.21 or later.
Unmet dependency listing:
	 - Mod 'Fabric Language Kotlin' (fabric-language-kotlin) 1.10.0+kotlin.1.9.0 requires version 0.14.21 or later of mod 'Fabric Loader' (fabricloader), but only the wrong version is present: 0.14.19!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.19.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
Process exited with code 1.
Clipboard copy at: 09 Jul 2023 02:23:54 -0700

**Comment by Juuxel** [comment]
See this message (which is a bit obscured in the log):

> Replace mod 'Fabric Loader' (fabricloader) 0.14.19 with version 0.14.21 or later.

You need to update your Fabric Loader to the latest version as well.
