### ISSUE TITLE
Top level function reference entry points don't work

### ISSUE THREAD

**Issue by opekope2** [FabricMC/fabric-language-kotlin#120]
As I described it in https://github.com/opekope2/OptiGUI/issues/80#issuecomment-1788893541, when I specify a top level function reference as an entry point.
After a recent change in Kotlin reflection (https://github.com/JetBrains/kotlin/commit/5dc882abf5727117d944fddeb934ecf92a8a4927, Kotlin 1.9.20), [`k.objectInstance`](https://github.com/FabricMC/fabric-language-kotlin/blob/88fb7d5066efdf75ae0b23203dc805f4bb057729/src/main/kotlin/net/fabricmc/language/kotlin/KotlinAdapter.kt#L62) returns `null` instead of throwing `UnsupportedOperationException`, so `KotlinAdapter` doesn't fall back to the default adapter.

**Comment by modmuss50** [comment]
Uhh, thats a sneaky change. Ill mark FLK with Kotlin 1.9.20 as a beta, and look into fixing this.

**Comment by modmuss50** [comment]
If you want a jar to test with: https://cdn.discordapp.com/attachments/789950127774105602/1169292378432098394/fabric-language-kotlin-1.10.11kotlin.1.9.20.local.jar
