### ISSUE TITLE
does not load with Sinytra Connector mod at all crashing on start up.

### ISSUE THREAD

**Issue by FullMetalMaster** [FabricMC/fabric-language-kotlin#124]
trying to get Cobblemon on fabric and some forged mods working together and this mod will not load in the SATA connector environment? if theres any fix for this it would be amazing
[latest.log](https://github.com/FabricMC/fabric-language-kotlin/files/13275771/latest.log)

**Comment by Linguardium** [comment]
If the connector is not properly handling mod compatibility, I would suggest you report the issue to the connector mod folks and not some random other mod issue tracker....

**Comment by FullMetalMaster** [comment]
i did so next update should be fixed thank you guys to for your hard work!

**Comment by modmuss50** [comment]
We dont support this, please use fabric-loader.
