### ISSUE TITLE
Kotlin JSR223 Support

### ISSUE THREAD

**Issue by Boundarybreaker** [FabricMC/fabric-language-kotlin#13]
Kotlin has a library called [`kotlin-scripting-jsr223-embeddable`](https://search.maven.org/artifact/org.jetbrains.kotlin/kotlin-scripting-jsr223-embeddable/1.3.50/jar). This allows it to be run from JSR-223 contexts, like the ones used for LibCD and Cotton Scripting. Would it be possible to add jsr223 kotlin scripting to Fabric Language Kotlin?

**Comment by natanfudge** [comment]
Don’t think this is related to this project.

**Comment by Boundarybreaker** [comment]
The embeddable lib is 23 KB. Any separate mod would need to depend on FLK, and it adds no bloat if nothing calls it, so no reason *not* to have it here.

**Comment by natanfudge** [comment]
Ok, I support this then.

**Comment by Juuxel** [comment]
That depends on `kotlin-compiler-embeddable` which is a 35MB dependency.

**Comment by Boundarybreaker** [comment]
Huh. Thought that FLK already included that.

**Comment by Boundarybreaker** [comment]
Ah, yeah. Guess a separate mod would be worth it then. I'll talk to Nikky about it sometime, since I don't know nearly enough about kotlin.

**Comment by natanfudge** [comment]
> That depends on kotlin-compiler-embeddable which is a 35MB dependency.

Hmm. That changes things

**Comment by modmuss50** [comment]
Yeah 35MB is a lot, the scala plug-in is 20MB so it’s doable but seems a bit excessive for one or two mods.

**Comment by Boundarybreaker** [comment]
I'll look into getting that done. This issue isn't really needed anymore.
