### ISSUE TITLE
Unsupported operations with Kotlin reflections (Potentially related to #120)

### ISSUE THREAD

**Issue by EmilyBjartskular** [FabricMC/fabric-language-kotlin#130]
Crash report: https://mclo.gs/f7kcvK1

This seems related to #120 but not quite the same.
Pinging @opekope2 for awareness.

Tested with FLK versions 1.10.10, 1.10.12, 1.10.15, 1.10.16.
Working on FLK 1.10.10.
Crashes on the latter versions.

**Comment by modmuss50** [comment]
Hi, can you reproduce this just with optigui? If not I wonder if there is a mod conflict here.

**Comment by EmilyBjartskular** [comment]
Indeed, with only FLK, Fabric API and OptiGUI enabled the game loads.
My apologies, I really should have checked that first, especially with no one else reporting an issue.
I guess this is a lesson not to jump to conclusions only based on a crash report.

**Comment by modmuss50** [comment]
No worries at all, the next thing to do would be to add back a handful of other mods at a time and try and narrow down what could be causing this.

**Comment by EmilyBjartskular** [comment]
I have isolated the conflict to OptiGUI, Cobblemon and FLK 1.10.12+

**Comment by modmuss50** [comment]
Ah nice,

I have had a look at Cobblemon and it seems to shadow the whole of Kotlin into its jar file, without correctly using FLK thus making it incompatible with any mod that uses FLK. It should either JIJ FLK or repackage Kotlin if it doesnt want to use FLK.

This is not something that I can fix here sadly, I would reccomend opening an issue with them.
