### ISSUE TITLE
Ask for your permission

### ISSUE THREAD

**Issue by DSLZL** [FabricMC/fabric-language-kotlin#131]
Hello, Fabric Language Kotlin creators.
I'm DSLZL, and I'm sorry for opening a new issue on your project that is completely unrelated, but I can only contact you on GitHub in China.
I'd like to ask if I can put this Fabric Language Kotlin you made into my modpack and release it in modrinth, because I don't know much about the license, so I'm here to ask for your opinion, and if my actions are violating your rights, I'm very sorry and delete the modpack and apologize immediately after seeing your reply.
The modpack link in modrinth is: [only-optimized](https://modrinth.com/modpack/only-optimized), if you don't see it, it's because it's still under review.
Sorry to interrupt you, but please forgive me for any inconvenience I may have if I do not obtain your permission.
(This passage is supported by Microsoft Translator, if you agree with my behavior, please do not delete this issue, so that I can provide evidence if I need it)
Thank you so much.

**Comment by AnAwesomGuy** [comment]
if the mod is on modrinth then it can be in a modrinth pack
(as long as your not directly packaging it and using the modrinth app to make it)

**Comment by DSLZL** [comment]
> if the mod is on modrinth then it can be in a modrinth pack如果模组在 Modrinth 上，那么它可以在 Modrinth 包中 (as long as your not directly packaging it and using the modrinth app to make it)（只要你不直接打包并使用 Modrinth 应用程序制作）
> 
> also, you should use discussions for this kind of stuff, as issues are for reporting issues此外，您应该对此类内容使用讨论，因为问题用于报告问题

I don't know, so I'm very sorry and thank you for your reply

**Comment by modmuss50** [comment]
Yes, you can include the mod in your modpack. Thanks.

**Comment by DSLZL** [comment]
> Yes, you can include the mod in your modpack. Thanks.

Thank you for your reply.
