### ISSUE TITLE
Minecraft Instance does not launch on quilt

### ISSUE THREAD

**Issue by KaijuInvincible** [FabricMC/fabric-language-kotlin#139]
When I launch my instance, my game crashes and it says to update my fabricloader but I am playing on quilt, how do I do this with Prism Launcher ?
[crash-2024-05-08_11.22.58.3098-quilt_loader.txt](https://github.com/FabricMC/fabric-language-kotlin/files/15246800/crash-2024-05-08_11.22.58.3098-quilt_loader.txt)

**Comment by modmuss50** [comment]
Only Fabric is supported.
