### ISSUE TITLE
Errors in generated kotlin project from fabric website

### ISSUE THREAD

**Issue by u9g** [FabricMC/fabric-language-kotlin#142]
![image](https://github.com/FabricMC/fabric-language-kotlin/assets/43508353/88156e01-00f7-45c3-b3f0-7f4a83904e25)

These errors show up in my IDE when using the mod generator on the website with mc 1.20.4 and enabling Kotlin support.

**Comment by jakobkmar** [comment]
You have to update IntelliJ IDEA.

**Comment by u9g** [comment]
That was the problem, thanks!
