### ISSUE TITLE
Fabric 1.21 crash with anvil

### ISSUE THREAD

**Issue by ZootieDod** [FabricMC/fabric-language-kotlin#144]
when i open lan server and my friend joins , he uses the anvil and as soon as he places something in the second slot he gets kicked and it crashes

[crash-2024-07-01_12.14.27-client.txt](https://github.com/user-attachments/files/16056984/crash-2024-07-01_12.14.27-client.txt)

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
