### ISSUE TITLE
Fabric Language Kotlin 1.10.20+kotlin.1.9.24 to 1.11.0+kotlin.2.0.0

### ISSUE THREAD

**Issue by MJRamon** [FabricMC/fabric-language-kotlin#145]
Is it safe to update Fabric Language Kotlin from "1.10.20+kotlin.1.9.24" to "1.11.0+kotlin.2.0.0"? Seems like a major update, will it break mods that depend on 1.9.x version?

**Comment by modmuss50** [comment]
Yes, all mods should be compatible. It is a major update but it doesnt affect mods that much.
