### ISSUE TITLE
"The game crashed whilst ticking screen"

### ISSUE THREAD

**Issue by Atomic-Dude** [FabricMC/fabric-language-kotlin#146]
![image](https://cdn.discordapp.com/attachments/833071481440960523/1259702040926359594/image.png?ex=668ca472&is=668b52f2&hm=767de06cada25ea453f0df3789bde83b7b5d6f6db2e9dc6bd928118f30b54ca9&)

This crash was thrown up by a friend's Minecraft client while trying to use a modded enchantment table on a port forwarded LAN server. 

Any ideas for a fix?

**Comment by solaritygh** [comment]
Can you post more of the error?

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
