### ISSUE TITLE
Latest update breaks Create Track map

### ISSUE THREAD

**Issue by Xylush** [FabricMC/fabric-language-kotlin#150]
I've already reported it in a couple of other places to cover ground. if I load the server with the version from 3 weeks ago it works perfectly fine. I load the server with the latest version it boot loops into crashes.

Server Crash Report:
https://pastebin.com/eYiETSYu

**Comment by Waoweens** [comment]
it seems to be this issue with Ktor: https://youtrack.jetbrains.com/issue/KTOR-7054
