### ISSUE TITLE
Use new Kotlin logo

### ISSUE THREAD

**Issue by Emirlol** [FabricMC/fabric-language-kotlin#153]
The mod's logo is still the old Kotlin logo on the [Modrinth](https://modrinth.com/mod/fabric-language-kotlin) and [CurseForge](https://legacy.curseforge.com/minecraft/mc-mods/fabric-language-kotlin) pages. I've seen that since #59 the mod itself is using the new logo, so I thought maybe this change could be applied to the mod pages as well.

**Comment by modmuss50** [comment]
Done! Thanks for pointing that out.
