### ISSUE TITLE
Update to kotlin 2.1.0

### ISSUE THREAD

**Issue by Emirlol** [FabricMC/fabric-language-kotlin#155]
2.1.0 is out: https://github.com/JetBrains/kotlin/releases/tag/v2.1.0

**Comment by modmuss50** [comment]
We have an automated update system that runs every 24 hours, it would likely have picked this up overnight, but ill kick it off again now.

**Comment by modmuss50** [comment]
Uhh, it looks like this is going to need a loom update to support the new metadata version.

**Comment by modmuss50** [comment]
Loom PR: https://github.com/FabricMC/fabric-loom/pull/1222

**Comment by monochandev** [comment]
the loom pr is merged, ETA on 2.1.0?

**Comment by modmuss50** [comment]
I need to get loom 1.9 fully released right now its still on the experimental branch.
