### ISSUE TITLE
Using kotlin.random.Random crashes with NoClassDefFoundError 

### ISSUE THREAD

**Issue by natanfudge** [FabricMC/fabric-language-kotlin#16]
This is the log 
![image](https://user-images.githubusercontent.com/25990014/69906482-a6bece00-13cc-11ea-85e5-a6dc8eaaab1b.png)

It happened in this project https://dilaton.martmists.com/martmists/realisticclouds

**Comment by NikkyAI** [comment]
i assume this uses jdk 9-12 ?
i would report this to kotlin (slack) first to see whats going on
or is there specific dependencies we miss to include >

**Comment by natanfudge** [comment]
This is using jdk8 (I think). I (or someone else) need to test it myself.

**Comment by NikkyAI** [comment]
i think we missed to include `org.jetbrains.kotlin:kotlin-stdlib-jdk7` and it is not transitive
i hope adding that fixes this

**Comment by natanfudge** [comment]
Wouldn't that mean we bundle both jdk8 and jdk7? That won't be good.

**Comment by NikkyAI** [comment]
jdk-7 is just 3.06 kb
