### ISSUE TITLE
Client Crash

### ISSUE THREAD

**Issue by VictorGamerLOL** [FabricMC/fabric-language-kotlin#17]
Everytime I use cauldronBrewing, potatocore and this mod(together) my client crashes. Here is what the developer console said: 
[eyyyyyyyy.txt](https://github.com/FabricMC/fabric-language-kotlin/files/3963995/eyyyyyyyy.txt)

**Comment by NikkyAI** [comment]
this has nothing to do with the kotlin module
look at the stacktrace in more detail `java.lang.RuntimeException: Failed to setup optifine`
