### ISSUE TITLE
Tag Fabric Language Kotlin as 1.16-snapshot compatible on CurseForge

### ISSUE THREAD

**Issue by adriantodt** [FabricMC/fabric-language-kotlin#19]
There is some confusion regarding using this mod because it is tagged as 1.14  ~ 1.15.2 compatible but not 1.16-snapshot compatible. I use this library in one of my mods and people are confused because it's tagged as 1.15.2 when I'm compiling my mod with it in the latest snapshots.

**Comment by NikkyAI** [comment]
well its compatible with ALL versions as logn as loader is new enough.. but curseforge won't allow that

i manually updated the lates few files on curseforge.. in the future i wonder if there is a bulk edit feature anywhere for that shitshow of a website..
