### ISSUE TITLE
Publish 1.4.0 to maven

### ISSUE THREAD

**Issue by MaryWeeb** [FabricMC/fabric-language-kotlin#23]
FLK 1.4.0 is available on Curseforge, but not on the fabricmc maven.

**Comment by modmuss50** [comment]
It should have been removed from both. As it was not supposed to have been released.

**Comment by MaryWeeb** [comment]
Is there an ETA for release? Blade upgraded to it, so my mod won't run without FLK 1.4.0

**Comment by modmuss50** [comment]
I merged the PR, but have no idea why its not on maven. You will have to wait for @NikkyAI or someone to point me in the right direction.

**Comment by modmuss50** [comment]
I have sorted this, please report any new issues.
