### ISSUE TITLE
Example in README uses unsupported Fabric Loader features

### ISSUE THREAD

**Issue by Juuxel** [FabricMC/fabric-language-kotlin#24]
```json
    "requires": {
        "fabric-language-kotlin": ">=1.4.0"
    }
```
As I pointed out [on #21](https://github.com/FabricMC/fabric-language-kotlin/pull/21#discussion_r481199015), `requires` a [deprecated and broken leftover](https://github.com/FabricMC/fabric-loader/blob/031235cfa3b028a75ab6d72ff5701648ff9fae5f/src/main/java/net/fabricmc/loader/metadata/ModMetadataV1.java#L116) from Loader versions before 0.4 and `depends` should be used instead.

Edit: this also affects the [sample json](https://github.com/FabricMC/fabric-language-kotlin/pull/22/files#diff-1c73cffcfa5f7da748b8624f73a7cb81L46-R50)

**Comment by modmuss50** [comment]
Fixed.
