### ISSUE TITLE
1.4.0 crashes on startup with Java 14

### ISSUE THREAD

**Issue by 2xsaiko** [FabricMC/fabric-language-kotlin#25]
It says the crash is in Adorn's entrypoint but I don't think that's actually the root cause, looking at the stack trace. It doesn't crash when used with Java 8.

https://paste.2x.ax/~saiko/e268bf2ef1c8e6200933770cf7e85abb16a177ca

Working Java version:
>openjdk version "1.8.0_252"
OpenJDK Runtime Environment (IcedTea 3.16.0) (Gentoo icedtea-3.16.0)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)

Broken Java version:
>openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment 14.0.2_p12 (build 14.0.2+12)
OpenJDK 64-Bit Server VM 14.0.2_p12 (build 14.0.2+12, mixed mode, sharing)

**Comment by modmuss50** [comment]
very odd.

**Comment by Juuxel** [comment]
It seems that it's kotlin-reflect being broken and getting used in the Kotlin language adapter. I'll switch to the default adapter in Adorn for now.

**Comment by NikkyAI** [comment]
i need better testing and actually install java 14 on my system
