### ISSUE TITLE
kotlinx.coroutines.core is missing in the released package on curseforge

### ISSUE THREAD

**Issue by DWVoid** [FabricMC/fabric-language-kotlin#26]

**Comment by DWVoid** [comment]
Did some research yesterday, turns out that it is now kotlinx.coroutines.core-jvm. Hope this would be helpful

**Comment by MaryWeeb** [comment]
...people actually use kotlinx coroutines?

**Comment by DWVoid** [comment]
it's a good tool for arranging async procedures. why not?

**Comment by modmuss50** [comment]
It should be, just missing an include I guess

**Comment by modmuss50** [comment]
Fixed, will be in the next version.
