### ISSUE TITLE
Failed - Virus scan failed 

### ISSUE THREAD

**Issue by kara1907** [FabricMC/fabric-language-kotlin#33]
i downloaded the program and it said Failed - Virus scan failed.
![Screenshot_3](https://user-images.githubusercontent.com/77941550/105645234-66ad8b00-5eab-11eb-9b52-f3dec42953eb.png)

**Comment by modmuss50** [comment]
Please ensure you are downloading from the official download site here: https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin/files

The scan is failing to run pointing to an issue on your end, and not suggesting that the file you downloaded is a virus. 

You can see the virus totally report of the latest version here: https://www.virustotal.com/gui/file/5c797764e952317b0e38f0c0b565cd18e2067bc73fbeb71afd6b22ffa5c2c8f5/detection

If you are still unsure you can always built it from the source code hosted on this github repo.

**Comment by kara1907** [comment]
i downloaded the program again and  it doesnt have any issues now, thanks.
