### ISSUE TITLE
Trojan detection:  Java.Trojan.GenericGBA.29492

### ISSUE THREAD

**Issue by Marek639** [FabricMC/fabric-language-kotlin#37]
Java.Trojan.GenericGBA.29492
Bitdefender gave me this after I manually scanned the mods folder. Is it a false positive? If so, then can u provide any proof of it being false? And yes, it was found in the Kotlin code.

**Comment by DeltaNedas** [comment]
yes it is a false positive, the code is right there for you to study and compile yourself.

**Comment by modmuss50** [comment]
Please make sure you are using an offical jar from https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin

**Comment by Marek639** [comment]
I wanted to download the latest version of the mod but Bitdefender just won't let me. The file D:\Downloads\Nepotvrdené 589949.crdownload has been detected as infected. The threat has been successfully blocked, your device is safe. So I'm so confused.

**Comment by modmuss50** [comment]
You can view the virus total report here: https://www.virustotal.com/gui/file/75a407232f970e35ca4be84d0962aec41d4487a19dbe6cae5057267d08e49728/detection If you are still unsure you can build it from source code.

**Comment by Marek639** [comment]
> Please make sure you are using an offical jar from https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin

I'm somehow not able to do that. IDK I'll probably just wait till BitDefender resolves the issue. This newer happed before
