### ISSUE TITLE
Deprecated ModMenu Stuff

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [FabricMC/fabric-language-kotlin#38]
This is put in logs when you load up fabric-language-kotlin: `[main/WARN]: WARNING! Mod fabric-language-kotlin is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.`

**Comment by Technici4n** [comment]
Closed by #43.
