### ISSUE TITLE
Kotlin 1.5.0 Support?

### ISSUE THREAD

**Issue by realSmushyTaco** [FabricMC/fabric-language-kotlin#41]

**Comment by Username404-59** [comment]
Kotlin 1.5.0 would be nice too

**Comment by modmuss50** [comment]
I will look into updating to 1.5. I wasn’t aware that it was released.

**Comment by modmuss50** [comment]
https://github.com/FabricMC/fabric-language-kotlin/commit/ab3585cfff4784307cb36e3f408476f222e1e172

This should do it, will release as a beta to begin with.
