### ISSUE TITLE
Using Deprecated Mod Menu API

### ISSUE THREAD

**Issue by realSmushyTaco** [FabricMC/fabric-language-kotlin#42]
`[12:54:45] [main/WARN] (Mod Menu) WARNING! Mod fabric-language-kotlin is only using deprecated 'modmenu:api' custom value! This will be removed in 1.18 snapshots, so ask the author of this mod to support the new API.`

Not sure if you guys are aware of this but I thought I would just notify you about this here!

**Comment by NinjaPhenix** [comment]
If anyone wants to tackle this, change:
```
"modmenu:api": true
```
to
```
"modmenu": {
  "badges": [
    "library"
  ]
}
```
