### ISSUE TITLE
UnsupportedOperationException error, removing kotlin 1.4.31 fixes it

### ISSUE THREAD

**Issue by hgorski6** [FabricMC/fabric-language-kotlin#44]
Crash log
https://pastebin.com/3hjdbAT4

**Comment by Juuxel** [comment]
Based on the log, this seems to be related to CBT/Connected Block Textures instead of Fabric Language Kotlin.

```
	at com.google.common.collect.ImmutableCollection.add(ImmutableCollection.java:218)
	at net.minecraft.class_3304.handler$zpd000$injectCBTPack(class_3304.java:2029)
	at net.minecraft.class_3304.method_18232(class_3304.java)
```
where `class_3304.method_18232` is `ReloadableResourceManagerImpl.beginMonitoredReload`

**Comment by hgorski6** [comment]
> Based on the log, this seems to be related to CBT/Connected Block Textures instead of Fabric Language Kotlin.
> 
> ```
> 	at com.google.common.collect.ImmutableCollection.add(ImmutableCollection.java:218)
> 	at net.minecraft.class_3304.handler$zpd000$injectCBTPack(class_3304.java:2029)
> 	at net.minecraft.class_3304.method_18232(class_3304.java)
> ```
> 
> where `class_3304.method_18232` is `ReloadableResourceManagerImpl.beginMonitoredReload`

Removing the mod has solved the issue, Thank you
