### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics

### ISSUE THREAD

**Issue by LittleLito** [FabricMC/fabric-language-kotlin#53]
when i use the jar that i found in my project's `build/libs` folder to test its working on common mc launcher(not inside intellij) and i got this:
`Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics`
i used kotlin in my project, but the main entry class is in java and i added fabric-language-kotlin in build.gradle's dependencies

**Comment by Juuxel** [comment]
Have you also installed FLK in the mc launcher mods directory? It needs to be there as well. (And preferably in your fabric.mod.json's `depends` section as well)

**Comment by LittleLito** [comment]
how can i install it?

**Comment by Juuxel** [comment]
You just need to download the FLK jar and put in it `mods` like any other mod.
