### ISSUE TITLE
Update version on Modrinth

### ISSUE THREAD

**Issue by NatoBoram** [FabricMC/fabric-language-kotlin#61]
The 1.6.5 and 1.7.0 versions are missing on [Modrinth](https://modrinth.com/mod/fabric-language-kotlin/versions)

**Comment by cadenkriese** [comment]
Would really appreciate this as my services use the modrinth download api

**Comment by cadenkriese** [comment]
Version 1.7.1 is up, so I think this can be closed, https://modrinth.com/mod/fabric-language-kotlin/version/nrHxebpS

**Comment by NatoBoram** [comment]
Hm. It's quite hard to confirm the latest version since the author doesn't use Git tags for versions...

I think it matches between CurseForge and Modrinth at least, so it should be good enough for all intents and purposes.
