### ISSUE TITLE
Tag versions

### ISSUE THREAD

**Issue by NatoBoram** [FabricMC/fabric-language-kotlin#62]
Whenever there's a new named version, it would be useful to [tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging) the commit that was used to build/publish it. This would allow people to build older versions and it makes good use of GitHub's [releases](https://github.com/FabricMC/fabric-language-kotlin/releases) tab

**Comment by modmuss50** [comment]
This was completed.
