### ISSUE TITLE
Crashes on latest version with nothing else but Fabric API

### ISSUE THREAD

**Issue by apotheoseGrifter** [FabricMC/fabric-language-kotlin#8]
The latest version crashes even with nothing else except the latest Fabric API (I wasn't sure if this mod needed it, but I figured it was better safe than sorry). I was only able to get it working by rolling back to version 1.3.30+build.2.

To try and eliminate the possibility of user error, I tested this on a fresh multimc instance downloaded from the install instructions template (mappings version 1.14+build.7 and loader version 0.4.6+build.141) with freshly-downloaded mod jars (Fabric API is version 0.2.7+build.127, Fabric Language Kotlin is version 1.3.31+build.2).

https://paste.ee/p/TSrPM

**Comment by ehamawy** [comment]
I am having the exact same issue, and also tested it in a fresh multimc instance before finding this thread.

Using an older version works, but is incompatible with some mods made to work only with the new one, which has been messing up modpack compatibility.

**Comment by NikkyAI** [comment]
sorry for ignoring this for so long, somehow github decided to just set this repo to `not watching`
the paste seems to be expired and since then 1.3.50 was released, i heard no complaints about that one so far

could you retry?
