### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by jonahdk** [FabricMC/fabric-language-kotlin#85]
Hello, whenever I try opening Fabric 0.14.9 using FLK (do people use that? if not they should), version 1.7.4 1.6.21 (It says that version does support 1.18.2). I would be using 1.7.3 1.6.20 since its native version is 1.18.2 but 3 of the other mods require 1.7.4 1.6.21, so I have to use that. Anyway, whenever I try opening the game, it crashes immediately. The pastebin for the error is https://pastebin.com/7BWFNEta

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
