### ISSUE TITLE
Unable to load kotlin.jvm.internal.Intrinsics from within a prelaunch entrypoint

### ISSUE THREAD

**Issue by Deftu** [FabricMC/fabric-language-kotlin#87]
The crash looks as follows: https://mclo.gs/hiNqUff

Nothing was changed in my mod aside from adding this entrypoint, so I'd assume it's this. I'm using the Kotlin adapter on the entrypoint.

**Comment by jakobkmar** [comment]
This is not a fabric-language-kotlin issue, your mod (or some other mod) is probably including FLK - which it shouldn't - since FLK is already loaded as a mod by itself.

**Comment by Deftu** [comment]
This was being caused by a corrupted mod file JIJ'ing FLK. Super weird result.
