### ISSUE TITLE
akuleshov7/ktoml inclusion

### ISSUE THREAD

**Issue by isXander** [FabricMC/fabric-language-kotlin#91]
It would be very useful if [`ktoml`](https://github.com/akuleshov7/ktoml) were to be included in this library. It works with `kotlinx.serialization` and TOML is an every growing format.

**Comment by Juuxel** [comment]
FLK doesn't include 3rd party libraries so that wouldn't make much sense IMO. Just JIJ it like any other library.

**Comment by isXander** [comment]
Another reason is that Kotlin/kotlinx-serialization#1092 states that plans for official TOML support aren't planned and TOML is quite a common config format in Minecraft mods nowadays.

**Comment by modmuss50** [comment]
I agree, we only include official kotlin libraries. You can easily JIJ it 👍
