### ISSUE TITLE
Display as library in Mod Menu

### ISSUE THREAD

**Issue by MightyKnight** [FabricMC/fabric-language-kotlin#94]
**Is your feature request related to a problem? Please describe.**
The mod appears in the normal Modmenu list, even if library mods are hidden.
Usually you would only want to see the userfacing mods and it might cause confusion, e.g. "I didn't install this".

**Describe the solution you'd like**
Modmenu provides a way to specify it in the fabric.mod.json:
```
"custom": {
  "modmenu": {
    "badges": [ "library" ]
  }
}
```

It will also display this badge
![grafik](https://user-images.githubusercontent.com/38622942/198753790-e82c2217-4366-4435-bf27-c470ab48a84b.png)

**Comment by Juuxel** [comment]
Fabric projects don't typically add Mod Menu badges since it's a third party mod. FLK actually had it at one point but it was removed since it didn't belong here: #43
